### ISSUE TITLE
Error: Cannot find module 'next' - Found Work-Around

### ISSUE THREAD

**Issue by Orange-418** [Vandivier/welephant#35]
>blitz dev
Loaded env from \.env
Error: Cannot find module 'next'
Require stack:
- \noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at resolveFileName (\npm\node_modules\blitz\node_modules\resolve-from\index.js:29:39)
    at resolveFrom (\npm\node_modules\blitz\node_modules\resolve-from\index.js:43:9)
    at module.exports (\npm\node_modules\blitz\node_modules\resolve-from\index.js:46:47)
    at module.exports (\npm\node_modules\blitz\node_modules\resolve-cwd\index.js:4:30)
    at resolveBinAsync (\npm\node_modules\blitz\dist\chunks\index2.cjs:105:44)
    at getCommandBin (\npm\node_modules\blitz\dist\chunks\index2.cjs:144:21)
    at Object.normalize (\npm\node_modules\blitz\dist\chunks\index2.cjs:140:20)
    at async Module.dev (\npm\node_modules\blitz\dist\chunks\next-commands.cjs:277:35)
    at async dev (\npm\node_modules\blitz\dist\chunks\dev.cjs:29:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '\\noop.js' ]
}

----> I worked around this and successfully got the app running by:
1. Creating a new default app through blitz, database with typescript, recommended dependencies
2. Dragged "node_modules" folder from the new default app folder to the "welephant-main" folder

Seems that the node_modules was missing from welephant_main.

I apologize if this is not an actual error, it's something I ran into and thought should share. I'm not familiar with submitting issues, critique is welcome.

**Comment by Orange-418** [comment]
Correction: You actually have to choose:
> blitz new app
> TypeScript
> Full
> y
**> React Hook Form**

I also had to drag package-lock.json into the welephant_main folder from the new app folder
